### PR TITLE
Update issue templates

### PR DESCRIPTION
**Pull request by joachimweyl**
new template for OpenShift Metrics and logs requests.

### CODE REVIEW

**Review by computate — CHANGES_REQUESTED** [review]
Can we please add one additional question?

`What is your NERC OpenShift project allocation name?`

**Comment by computate** [comment]
Thanks for creating this @joachimweyl , I know now how to create a PR in the future.

**Comment by joachimweyl** [comment]
done, would you like this assigned to anyone by default?

**Review by computate — APPROVED** [review]

**Comment by computate** [comment]
@joachimweyl you can auto-assign to @computate

**Pull request merged**
